name: CI Workflow

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create reports directory
      run: mkdir -p reports

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q --html=reports/test_report.html --self-contained-html

    - name: Run linting with flake8
      run: |
        flake8 --max-line-length=120 --format=html --htmldir=reports/flake8-html

    - name: Upload test report to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/test_report.html

    - name: Upload linting report to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: reports/flake8-html
